export const demo2_1 = [
  {
    id: "p0s0",
    text: "China eyes 'dragon' baby boom",
  },
  {
    id: "p1s0",
    text: "Chinese demographers predicted that the \"dragon baby fever\" is likely to cause a small baby boom this year, a positive sign of people's confidence in China's economy and social policies. ",
  },
  {
    id:"p2s0",
    text:"A surge in pregnancy  "

  },
  {
    id:"p3s0",
    text: "The Dragon is undoubtedly the most favored sign among all the 12 Chinese zodiacs or animal signs.",
    pos: "most favored",
    value1: "1",
    type: "extreme",
    attribute: "maximum",
  },
  {
    id:"p4s0",
    text:"Many Chinese people refer to themselves as \"descendants of the dragon.\" ",
  },
  {
    id:"p4s1",
    text:"On China's lifestyle-oriented social media app Little Red Book, or Xiaohongshu, a recent survey covering some 148,000 users showed that almost one in three respondents like the dragon the most, unsurprisingly ranking top among all the 12 animal signs.",
    pos: "top",
    entity1: "dragon",
    value1: "1",
    type: "rank",
  },
  {
    id:"p5s0",
    text:"Chinese people's preference for \"dragon babies\" has been intuitively reflected in hospitals. Across the country, many hospitals revealed that the numbers of pregnant and \"lying-in\" women have surged in the last two or three months.",
    entity1: 'doctors-in-training', 
    value1: 'NAN', 
    value2: 'NAN',
    value3: 'NAN',
    pos: 'number',
    type: "trend",
    attribute: "positive",
  },
  {
    id:"p6s0",
    text:"In Shanghai, several major maternity hospitals have seen an increase in the number of obstetrics service registrations. ",
    entity1: 'doctors-in-training', 
    value1: 'NAN', 
    value2: 'NAN',
    value3: 'NAN',
    pos: 'seen',
    type: "trend",
    attribute: "positive",
  },
  {
    id:"p6s1",
    text:"At the Obstetrics & Gynecology Hospital of Fudan University, the number in January grew by 14 percent compared to the same period in 2021.",
    entity1: 'number in January', 
    entity2: 'same period in 2021', 
    value1: '14', 
    value2: '0',
    value3: '14',
    pos: 'grew',
    type: "comparison",
  },
  {
    id:"p6s2",
    text:"Its previous obvious growth was in 2012, also a Year of the Dragon, Gu Weirong, deputy director of the hospital, told local media Shanghai Observer.",
  },
  {
    id:"p7s0",
    text:"In Beijing, a woman surnamed Yang said she learned from medical staff that the workload of the department's ultrasound room at the end of 2023 was up to four times that of the same period in 2022.",
    entity1: 'the workload of the department\'s ultrasound room at the end of 2023', 
    entity2: 'the workload of the department\'s ultrasound room at the same period in 2022', 
    value1: 'four times', 
    value2: 'NAN',
    value3: '3',
    pos: 'was',
    type: "comparison",
  },
  {
    id:"p8s0",
    text:"Chinese think tank YuWa Population Research on Wednesday released a report on the cost of raising a child in China. According to the report, which is based on the China Statistical Yearbook 2023, in 2022, the average cost of raising a child from birth to the age of 17 in China was 538,000 yuan ($7,372). ",


  },
  {
    id:"p9s0",
    text: "When compared with GDP, the average cost of raising a child in China until the age of 18 was 6.3 times China's GDP per capita in 2022,",
    entity1: 'average cost of raising a child in China until the age of 18', 
    entity2: 'China\'s GDP per capita in 2022', 
    value1: '6.3', 
    value2: 'NAN',
    value3: 'NAN',
    pos: 'GDP',
    type: "comparison",
  },
  {
    id:"p9s1",
    text: "higher than many countries including Japan (4.26 times), the US (4.11 times), and Germany (3.64 times), read the report.",
    entity1: 'Japan', 
    entity2: 'the US', 
    value1: '4.26', 
    value2: '4.11',
    value3: '0.15',
    pos: 'grew',
    type: "comparison",
  },
  {
    id:"p10s0",
    text: "Chinese authorities have made various efforts to help reduce fertility costs in recent years,",
  },
  {
    id:"p11s0",
    text: "Some demographers believed the possible temporary baby boom in the Year of the Dragon is unlikely to change the overall trend of declining birth rates, but it is nonetheless a positive sign.",
    entity1: 'doctors-in-training', 
    value1: 'NAN', 
    value2: 'NAN',
    value3: 'NAN',
    pos: 'number',
    type: "trend",
    attribute: "positive",
  },
  {
    id:"p12s0",
    text: "Many more boys than girls?",
  },
  {
    id:"p13s0",
    text:"China's sex ratio at birth is another widely watched figure apart from the general fertility rate.",
  },
  {
    id:"p14s0",
    text:"In China, the sex ratio at birth in 2022 was 111.1 (111.1 boys per 100 girls), slightly increased from the previous year's 108.3 ratio, according to data from the National Health Commission. ",
    entity1: 'Japan', 
    entity2: 'the US', 
    value1: '111.1', 
    value2: '108.3',
    value3: '2.8',
    pos: 'grew',
    type: "comparison",
    },
    {
      id:"p14s1",
      text:"On social media, some users shared their observations of \"many more boys than girls in kindergarten,\" which resonated with many.",
    },
    {
      id:"p15s0",
      text:"However, the slight fluctuation in sex ratio at birth in one or two single years is normal."
    },
    {
      id:"p16s0",
      text:"Prior to 2022, China's sex ratios at birth saw a 10-year consecutive decrease, dropping from 117.7 in 2012 to 108.3 in 2021. ",
      value1: '117.7', 
      value2: '108.3',
      value3: '-9.4',
      pos: 'number',
      type: "trend",
      attribute: "negative",
    },
    {
      id:"p16s1",
      text:"The gender structure of the birth population has improved significantly, according to National Bureau of Statistics.",
    }
]